name: Sync
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'wip')"
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
          source-repo: "git@github.com:9527q/diagram-tcpip-note.git"
          destination-repo: "git@gitee.com:q9527q/diagram-tcpip-note.git"
    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          gitee-username: q9527q
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: q9527q/diagram-tcpip-note
          branch: gh-pages